name: CI

on:
  push:
    branches:
      - test/ci-check           # 여기 main을 잠시 test/ci-check로 변경!!!

jobs:
  detect-pr:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.pr.outputs.pr_number }}
    steps:
      - uses: actions/checkout@v4
      - name: Find PR
        id: pr
        run: |
          PR_NUMBER=$(gh pr list \
            --repo "${{ github.repository }}" \
            --state closed \
            --json number,mergeCommit \
            --jq ".[] | select(.mergeCommit.oid == \"${{ github.sha }}\") | .number")

          echo "pr_number=${PR_NUMBER}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: detect-pr
    # if: needs.detect-pr.outputs.pr_number != ''     # 테스트해보려고 주석 처리합니다~
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set PR Number
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state closed --json number,mergeCommit --jq ".[] | select(.mergeCommit.oid == \\"${{ github.sha }}\\") | .number")
          echo "PR_NUMBER=${PR_NUMBER}"
          echo "PR_NUMBER"="${PR_NUMBER}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Set Docker Image Tag
        id: get_pr_number
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state closed --json number,mergeCommit --jq ".[] | select(.mergeCommit.oid == \\"${{ github.sha }}\\") | .number")
          DOCKER_IMAGE_TAG="test-v1"          
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}"
          echo "DOCKER_IMAGE_TAG"="${DOCKER_IMAGE_TAG}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        env:
          DOCKER_IMAGE_TAG: ${{ steps.get_pr_number.outputs.DOCKER_IMAGE_TAG }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ env.DOCKER_IMAGE_TAG }} .

      - name: Push Docker Image
        env:
          DOCKER_IMAGE_TAG: ${{ steps.get_pr_number.outputs.DOCKER_IMAGE_TAG }}
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ env.DOCKER_IMAGE_TAG }}


#  DOCKER_IMAGE_TAG="test=v1"  # <----  # DOCKER_IMAGE_TAG="1.0.$PR_NUMBER" 원래는 이렇게 해야 하지만, 여기도 테스트해보려고 잠시 이렇게 바꾼겁니다! 나중에 main에 올릴 때는 다시 바꿔
#  48번!